name: druid-mautic
recipe: lamp
config:
  webroot: docroot
  php: "8.2"
  database: mysql:5.7

tooling:
  mt:
    service: appserver
    description: Run Mautic commands
    cmd: php bin/console
  node:
    service: appserver
  npm:
    service: appserver

proxy:
  mailhog:
    - mail.mautic-contrib.lndo.site

services:
  mailhog:
    type: mailhog
    portforward: true
    platform: linux/amd64

  appserver:
    type: php:8.2
    build_as_root:
      - apt-get update && apt-get install -y cron libc-client-dev libkrb5-dev
      - docker-php-ext-configure imap --with-kerberos --with-imap-ssl=/usr/lib/x86_64-linux-gnu
      - docker-php-ext-install imap sockets
      - curl -sL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
    xdebug: true
    config:
      php: .lando/php/php.ini
