<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYDI2OxB\AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYDI2OxB/AppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerYDI2OxB.legacy');

    return;
}

if (!\class_exists(AppKernelProdContainer::class, false)) {
    \class_alias(\ContainerYDI2OxB\AppKernelProdContainer::class, AppKernelProdContainer::class, false);
}

return new \ContainerYDI2OxB\AppKernelProdContainer([
    'container.build_hash' => 'YDI2OxB',
    'container.build_id' => '610844d4',
    'container.build_time' => 1733682146,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYDI2OxB');
