<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\CoreExtension;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;
use Twig\TemplateWrapper;

/* @bundles/CategoryBundle/Translations/en_US/messages.ini */
class __TwigTemplate_503cc231047c88db93afc417dccde166 extends Template
{
    private Source $source;
    /**
     * @var array<string, Template>
     */
    private array $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = []): iterable
    {
        $macros = $this->macros;
        // line 1
        yield "mautic.category.createnew=\"Create new category...\"
mautic.category.form.alias.help=\"Letters and numbers (hyphens allowed) used for URL generation of this category. A unique alias based on the title will be autogenerated if left empty.\"
mautic.category.form.confirmbatchdelete=\"Delete the selected categories? Associated items will NOT be deleted but will be assigned as uncategorized.\"
mautic.category.form.confirmdelete=\"Delete the category, %name%? Associated items will NOT be deleted but will be assigned as uncategorized.\"
mautic.category.global=\"Global\"
mautic.category.header.edit=\"Edit %type% Category - %name%\"
mautic.category.header.index=\"Categories\"
mautic.category.header.new=\"New Category\"
mautic.category.menu.index=\"Categories\"
mautic.category.noresults.tip=\"Categories help organize and group items together. In many of the filters, you can type category:{alias} (replace {alias} with the real deal) to show the items within a specific category.\"
mautic.category.permissions.categories=\"Categories - User has access to\"
mautic.category.permissions.header=\"Category Permissions\"
mautic.global.global=\"Global\"";
        yield from [];
    }

    /**
     * @codeCoverageIgnore
     */
    public function getTemplateName(): string
    {
        return "@bundles/CategoryBundle/Translations/en_US/messages.ini";
    }

    /**
     * @codeCoverageIgnore
     */
    public function getDebugInfo(): array
    {
        return array (  42 => 1,);
    }

    public function getSourceContext(): Source
    {
        return new Source("", "@bundles/CategoryBundle/Translations/en_US/messages.ini", "/app/docroot/app/bundles/CategoryBundle/Translations/en_US/messages.ini");
    }
}
